# удаление ufw / создание .ssh/authorized_keys /настройка timezone
# установка минимально нужного софта / рестарт ОС
---
- name: First setup
  hosts: all
  become: yes
  vars:
    source_file:                                 # копируем ключи нужных специалистов 
    destin_file: 
    
  tasks:
  - name: Check and Print LINUX Version
    debug: var=ansible_os_family

  - block: # ======== Block for Debian/Ubuntu =========    
      - name: Remove service UFW (Uncomplicated Firewall) for Ubuntu 16 
        apt: name={{ item }} state=removed
        with_items:
          - ufw
        when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 16

      - name: Remove service UFW (Uncomplicated Firewall) for Ubuntu 18 
        apt: name={{ item }} state=removed
        with_items:
          - ufw
        when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 18

      - name: Creates directory = /root/.ssh/ 
        file:
          path: /root/.ssh/
          state: directory
          owner: root
          group: root
          mode: 0600
    
      - name: Copy authorized_keys in directory = /root/.ssh/
        copy: src={{ source_file }} dest={{ destin_file }} mode=0600 owner=root group=root

      - name: Modifying config file /etc/ssh/sshd_config 
        lineinfile:
          dest: "/etc/ssh/sshd_config"
          regexp: "^#PasswordAuthentication yes"
          line: "PasswordAuthentication no"
        notify: Reload sshd

      - name: set timezone to Europe/Moscow
        timezone:
          name: Europe/Moscow

      - name: Ensure a locale exists
        locale_gen:
          name: "{{ item }}"
          state: present
        with_items:
          - en_US.UTF-8
          - ru_RU.UTF-8
 
      - name: Install basic packages for Debian/Ubuntu
        apt: name={{ item }} state=installed update_cache=yes
        with_items:
         - net-tools
         - nano
         - mc
         - htop
         - sysstat
         - traceroute
         - tree
         - wget
         - zip
         - unzip
         - sshfs
         - mercurial
         - git
         - dnsutils

      - name: Restart Debian/Ubuntu server
        shell: sleep 3 && shutdown -r now
        async: 1
        poll: 0

    when: ansible_os_family == "Debian"
  handlers:
  - name: Reload sshd
    service: name=sshd.service state=reloaded