---
- name: Start service zabbix-agent
  service: 
    name: zabbix-agent
    state: started

- name: Creates directory = "{{ zabbix_path }}" 
  file:
    path: "{{ zabbix_path }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode_zabbix }}"

- name: Generate ZABBIX_AGENT.J2 file for LXC Debian/Ubuntu
  template: src=zabbix_agentd.j2 dest={{ destin_file }}/zabbix_agentd.conf
            owner="{{ owner }}" group="{{ group }}" mode="{{ mode }}"
  notify:
    - Restart zabbix_agent
  when: ansible_virtualization_type == "lxc" and ansible_os_family == "Debian"

- name: Generate ZABBIX_AGENT.J2 file for KVM Debian/Ubuntu
  template: src=zabbix_agentd.j2 dest={{ destin_file }}/zabbix_agentd.conf
            owner="{{ owner }}" group="{{ group }}" mode="{{ mode }}"
  notify:
    - Restart zabbix_agent
  when: ansible_virtualization_type == "kvm" and ansible_os_family == "Debian"

- name: Copy user parameter for LXC Containers   
  copy: src=zabbix_container.conf dest={{ destin_files }} mode="{{ mode }}"
  notify:
    - Restart zabbix_agent
  when: ansible_virtualization_type == "lxc"

- name: Copy user parameter for KVM    
  copy: src=zabbix_proxmox.conf dest={{ destin_filess }} mode="{{ mode }}"
  notify:
    - Restart zabbix_agent
  when: ansible_virtualization_type == "kvm" 

- name: Enable service zabbix-agent
  service: 
    name: zabbix-agent
    enabled: yes