---
# tasks file for Unlock_Users
- name: Unlock (Разблокировать) Users in "tadb"
  become: yes
  become_method: sudo
  become_user: postgres
  shell: psql -c "update tbl_user set is_locked = false where labels not like '%INACTIVE%';" tadb

