---
# tasks file for Unlock_User_TA
- name: Unlock (Разблокировать) ta Users in "tadb"
  tags: Unlock
  become: yes
  become_method: sudo
  become_user: postgres
  shell: psql -c "alter user ta with login;"

