all:
    vars_files:
        - variable.yml
    hosts:
      remote:
        ansible_connection: ssh
        ansible_user: "{{ user_to_connect  }}" # Remote user
        ansible_host: "{{ srv_1_ip_address }}" # Remote host
        ansible_port: "{{ srv_1_port_connect }}"