# Копирование конфиг файла с нужными параметрами для ОС (hostname/ip адрес)
---
- hosts: all
  become: yes
  vars:
    source_file: 
    destin_file: /etc/zabbix/

    source_files: *zabbix_container.conf
    destin_files: /etc/zabbix/zabbix_agentd.d/zabbix_container.conf
    
    source_filess: *zabbix_proxmox.conf
    destin_filess: /etc/zabbix/zabbix_agentd.d/zabbix_proxmox.conf

  tasks:
  - name: Check and Print LINUX Version
    debug: var=ansible_os_family

  - block: # ======== Block for RedHat =========
      - name: Copy file for RedHat
        copy: #src={{ source_file }} dest={{ destin_file }} mode=0644
        notify: 
            - restart zabbix_agent
    when: ansible_os_family == "RedHat"

  - block: # ======== Block for Debian/Ubuntu =========  
      - name: Start service zabbix-agent
        service: 
          name=zabbix-agent 
          state=started
      
      - name: Generate ZABBIX_AGENT.J2 file for Debian/Ubuntu
        template: src={{ source_file }}/zabbix_agentd.j2 dest={{ destin_file }}/zabbix_agentd.conf mode=0644
        notify:
          - Restart zabbix_agent
        when: ansible_virtualization_type == "lxc" and ansible_os_family == "Debian"

      - name: Generate ZABBIX_AGENT.J2 file for Proxmox/Debian
        template: src={{ source_file }}/zabbix_agentd.j2 dest={{ destin_file }}/zabbix_agentd.conf mode=0644
        notify:
          - Restart zabbix_agent
        when: ansible_virtualization_type == "kvm" and ansible_os_family == "Debian"

      - name: Copy user parameter for LXC Containers   
        copy: src={{ source_files }} dest={{ destin_files }} mode=0644
        notify:
          - Restart zabbix_agent
        when: ansible_virtualization_type == "lxc" 

      - name: Copy user parameter for Proxmox   
        copy: src={{ source_filess }} dest={{ destin_filess }} mode=0644
        notify:
          - Restart zabbix_agent
        when: ansible_virtualization_type == "kvm" 
        
      - name: Enable service zabbix-agent
        service: 
          name: zabbix-agent
          enabled: yes

  handlers:
  - name: Restart zabbix_agent
    service: 
      name=zabbix-agent
      state=restarted
  
