---
- name: Install basic packages for Debian/Ubuntu
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - net-tools
    - nano
    - mc
    - htop
    - sysstat
    - traceroute
    - tree
    - wget
    - zip
    - unzip
    - screen
    - curl
    - ethtool
    - dnsutils