---
# tasks file for Lock_Users  
- name: Lock (Блокировка) Users in "tadb"
  tags: Lock
  become: yes
  become_method: sudo
  become_user: postgres
  shell: psql -c "update tbl_user set is_locked = true where labels not like '%TEST%';" tadb
