---
# sudo apt-get install *
- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
    - curl

# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# sudo apt-key fingerprint 0EBFCD88
- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian version stable"
- name: Set up the stable repository for Debian 
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"

# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian version stable"
- name: Set up the stable repository for Ubuntu
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes

# sudo apt-get install docker-ce
- name: Install docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: Start docker on boot

# sudo groupadd docker
- name: Create "docker" group
  group:
    name: "{{ docker_group }}"
    state: present

# sudo usermod -aG docker root
- name: Add remote "remote_user" user to "docker_group" group
  user:
    name: "{{ remote_user }}"
    group: "{{ docker_group }}"
    append: yes

# Install docker-compose
- name: Install docker-compose
  get_url: 
    url: "{{ docker_compose_version }}" 
    dest: "{{ docker_compose_path }}"
    mode: 0755